name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node LTS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Checkout Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: deepl-x
          entrypoint: main.ts
          root: .
